// Class Info: This class is used to generate test data to /data/student.csv and /data/employRecord.csv

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Random;
import java.util.Scanner;

public class testDataGenerator {

    //define HashSets to store unique data.
    //Student ID must be unique.
    //employ ID must be unique.

    static HashSet<String> studentIdSet = new HashSet<>();
    static HashSet<String> employIdSet = new HashSet<>();

    public class student {
        String name; // read from /data/demoData/possibleFirstNames.csv and /data/demoData/possibleLastNames.csv
        String studentId; // Generated by the system, this wont be the case for real data.
        String major; // read from /data/demoData/possibleMajors.csv
        //Major can be categorized into different categories. However this is not the responsibility of this class. Check the Python code for more details.
        String email; // read from /data/demoData/possibleEmails.csv
        String phoneNumber; // read from /data/demoData/possiblePhoneNumbers.csv

        public student(String name, String studentId, String major, String email, String phoneNumber) {
            //use setters to set data.
            setName(name);
            setStudentId(studentId);
            setMajor(major);
            setEmail(email);
            setPhoneNumber(phoneNumber);
        }

        //setter must check if the data is unique.
        public void setName(String name) {
            if (name == null || name.isEmpty()) {
                throw new IllegalArgumentException("Name cannot be null or empty");
            }
            this.name = name;
        }
        public void setStudentId(String studentId) {
            if (studentId == null || studentId.isEmpty()) {
                Random random = new Random();
                while (true) {
                    studentId = "S" + random.nextInt(1000000); // Generate a random student ID
                    if (!studentIdSet.contains(studentId)) {
                        break; // Unique ID found
                    }
                }
            }
            if (studentIdSet.contains(studentId)) {
                throw new IllegalArgumentException("Student ID must be unique");
            }
            this.studentId = studentId;
            studentIdSet.add(studentId);
        }
        public void setMajor(String major) {
            this.major = major;
        }
        public void setEmail(String email) {
            this.email = email;
        }
        public void setPhoneNumber(String phoneNumber) {
            this.phoneNumber = phoneNumber;
        }
    }

    public class employRecord {
        String employId; // Generated by the system, this wont be the case for real data.
        String studentId; // studentId must exist in studentIdSet.
        String companyName; //read from /data/demoData/possibleCompanyNames.csv
        String position; // read from /data/demoData/possiblePositions.csv
        int salary; // Generated by the system, this wont be the case for real data, -1 if not set.
        Date startDate; // verified by java
        Date endDate;  // verified by java
        public employRecord(String employId, String studentId, String companyName, String position, int salart, Date startDate, Date endDate, Date currentDate) {
            //use setters to set data.
            setEmployId(employId);
            setStudentId(studentId);
            setCompanyName(companyName);
            setPosition(position);
            setSalary(salart);
            setStartDate(startDate);
            setEndDate(endDate, currentDate);
        }
        //setter must check if the data is unique.
        public void setEmployId(String employId) {
            if (employId == null || employId.isEmpty()) {
                Random random = new Random();
                while (true) {
                    employId = "E" + random.nextInt(1000000); // Generate a random employ ID
                    if (!employIdSet.contains(employId)) {
                        break; // Unique ID found
                    }
                }
            }
            if (employIdSet.contains(employId)) {
                throw new IllegalArgumentException("Employ ID must be unique");
            }
            this.employId = employId;
            employIdSet.add(employId);
        }
        public void setStudentId(String studentId) {
            // student must exist in studentIdSet.
            if (!studentIdSet.contains(studentId)) {
                throw new IllegalArgumentException("Student ID must exist");
            }
            this.studentId = studentId;
        }
        public void setCompanyName(String companyName) {
            this.companyName = companyName;
        }
        public void setPosition(String position) {
            this.position = position;
        }
        public void setSalary(int salary) {
            if (salary < 0) {
                salary = salaryGenerator(); // Generate a random salary
            }
            this.salary = salary;
        }
        public void setStartDate(Date startDate) {
            // compare startDate with current time

        }
        public void setEndDate(Date endDate, Date currentDate) {

            //1. compare endDate with startDate

            //2. check if endDate is greater than current time
            
        }

        int salaryGenerator() {
            // Generate a random salary between 30000 and 100000
            Random random = new Random();
            return 30000 + random.nextInt(70001);
        }
    }
    

    public static void main(String[] args) {
        // Ask the user for the number of students and employ records to generate
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter the number of students to generate: ");
        int numStudents = scanner.nextInt();
        System.out.print("Enter the number of employ records to generate: ");
        int numEmployRecords = scanner.nextInt();
        scanner.nextLine(); // Consume the newline character

        // Get current date

        // Create a list to store the students and employ records
        ArrayList<student> students = new ArrayList<>();
        ArrayList<employRecord> employRecords = new ArrayList<>();

        // Generate random student data for testing
        // not finished yet

    }

}